FROM dockerfile/java:oracle-java8

ADD spring-boot-examples.jar /opt/spring-boot-examples/
EXPOSE 8081
WORKDIR /opt/spring-boot-examples/
CMD ["java", "-Xms1g", "-Xmx1g", "-jar", "spring-boot-examples.jar"]